// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/personal": {
    params: {};
  };
  "/dashboard/add-product": {
    params: {};
  };
  "/dashboard/product": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/forgot-password" | "/register" | "/dashboard" | "/dashboard/personal" | "/dashboard/add-product" | "/dashboard/product" | "/*";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/auth/layout.tsx": {
    id: "routes/auth/layout";
    page: "/login" | "/forgot-password" | "/register";
  };
  "routes/auth/login/login.tsx": {
    id: "routes/auth/login/login";
    page: "/login";
  };
  "routes/auth/forgot-password/forgot-password.tsx": {
    id: "routes/auth/forgot-password/forgot-password";
    page: "/forgot-password";
  };
  "routes/auth/register/register.tsx": {
    id: "routes/auth/register/register";
    page: "/register";
  };
  "./routes/dashboard/private-route.tsx": {
    id: "routes/dashboard/private-route";
    page: "/dashboard" | "/dashboard/personal" | "/dashboard/add-product" | "/dashboard/product";
  };
  "./routes/dashboard/layouts.tsx": {
    id: "routes/dashboard/layouts";
    page: "/dashboard" | "/dashboard/personal" | "/dashboard/add-product" | "/dashboard/product";
  };
  "routes/dashboard/dashboard.tsx": {
    id: "routes/dashboard/dashboard";
    page: "/dashboard" | "/dashboard/personal" | "/dashboard/add-product" | "/dashboard/product";
  };
  "routes/dashboard/profile/profile.tsx": {
    id: "routes/dashboard/profile/profile";
    page: "/dashboard/personal";
  };
  "routes/dashboard/add-product/add-product.tsx": {
    id: "routes/dashboard/add-product/add-product";
    page: "/dashboard/add-product";
  };
  "routes/dashboard/table-data/table-data.tsx": {
    id: "routes/dashboard/table-data/table-data";
    page: "/dashboard/product";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/./routes/home.tsx");
  "routes/auth/layout": typeof import("./app/./routes/auth/layout.tsx");
  "routes/auth/login/login": typeof import("./app/routes/auth/login/login.tsx");
  "routes/auth/forgot-password/forgot-password": typeof import("./app/routes/auth/forgot-password/forgot-password.tsx");
  "routes/auth/register/register": typeof import("./app/routes/auth/register/register.tsx");
  "routes/dashboard/private-route": typeof import("./app/./routes/dashboard/private-route.tsx");
  "routes/dashboard/layouts": typeof import("./app/./routes/dashboard/layouts.tsx");
  "routes/dashboard/dashboard": typeof import("./app/routes/dashboard/dashboard.tsx");
  "routes/dashboard/profile/profile": typeof import("./app/routes/dashboard/profile/profile.tsx");
  "routes/dashboard/add-product/add-product": typeof import("./app/routes/dashboard/add-product/add-product.tsx");
  "routes/dashboard/table-data/table-data": typeof import("./app/routes/dashboard/table-data/table-data.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};